name: Build Jar 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Publish JAR
        uses: actions/upload-artifact@v2
        with:
          name: Dobby JAR
          path: build/libs
