name: Release 
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Release Version
run-name: ${{ inputs.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Publish JAR
        uses: actions/upload-artifact@v3
        with:
          name: Dobby JAR
          path: build/libs/dobby*RELEASE.jar
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: build/libs/dobby*RELEASE.jar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
